// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_cleanarchitecture_with_tdd/test/features/number_trivia/domain/usecases/get_concrete_number_trivia.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_cleanarchitecture_with_tdd/core/error/failures.dart'
    as _i6;
import 'package:flutter_cleanarchitecture_with_tdd/features/number_trivia/domain/entities/number_trivia.dart'
    as _i7;
import 'package:flutter_cleanarchitecture_with_tdd/features/number_trivia/domain/repositories/number_trivia_repository.dart'
    as _i3;
import 'package:flutter_cleanarchitecture_with_tdd/features/number_trivia/domain/usecases/get_concrete_number_trivia.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

import 'get_concrete_number_trivia.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeNumberTriviaRepository_1 extends _i1.Fake
    implements _i3.NumberTriviaRepository {}

/// A class which mocks [MockNumberTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockNumberTriviaRepository extends _i1.Mock
    implements _i4.MockNumberTriviaRepository {
  MockMockNumberTriviaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>> getConcreteNumberTrivia(
          int? number) =>
      (super.noSuchMethod(Invocation.method(#getConcreteNumberTrivia, [number]),
          returnValue: Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>>.value(
              _FakeEither_0<_i6.Failure, _i7.NumberTrivia>())) as _i5
          .Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>>
      getRandomNumberTrivia() =>
          (super.noSuchMethod(Invocation.method(#getRandomNumberTrivia, []),
                  returnValue:
                      Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>>.value(
                          _FakeEither_0<_i6.Failure, _i7.NumberTrivia>()))
              as _i5.Future<_i2.Either<_i6.Failure, _i7.NumberTrivia>>);
}

/// A class which mocks [GetConcreteNumberTrivia].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConcreteNumberTrivia extends _i1.Mock
    implements _i8.GetConcreteNumberTrivia {
  MockGetConcreteNumberTrivia() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NumberTriviaRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue: _FakeNumberTriviaRepository_1())
          as _i3.NumberTriviaRepository);
}
